name: my first workflow 

on: push

jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: welcome message
          run: echo "this is my first github actions job"

        - name: list file
          run: ls

        - name: read files
          run: cat README.md