name: my first workflow 

on: push

jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and Read file
          run: |
            echo "this is my first github actions job"
            ls -ltra
            cat README.md

        - name: Generate a ASCII artwork
          run: cowsay -f dragon "run for cover, i am a dragon......RAWR" >>dragon.txt



       # - name: list file
       #   ,rrun: ls

       # - name: read files
       #   run: cat README.md