name: Generate a Ascii workflow

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v4

    - name: list repo files
      run: ls -ltra

    - name: excuting shell script
      run: ./ascii-scrpit.sh

    
   
