name: Matrix configuration

on:
    push:
    workflow_dispatch:
    
jobs:
    deploy:
        strategy:
            #fail-fast: false
            #max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-20.08, windows-latest]
                images: [hello-world, alpine]
                exclude:
                - os: windows-latest
                  images: alpine

        runs-on: ${{matrix.os}}

        steps:
        - name: echo doker details
          run: docker info

        - name : run image on ${{matrix.os}}
          run: docker run ${{matrix.images}}

