name: workflow filters and activities in triggers.
on:
    workflow_dispatch: 

    push:
       # branches-ignore: 
         #   - features/* #features/add-music or features/updateimages
         #   - test/**   # test/ui/desk or test/checkout/payment
        branches: 
            - main
            - '!feature/*'  # ignoring pushing to any branch name starting with feature using !
    pull_request:
        types:
          - opened
          - closed
        paths-ignore:   # a workfilw only run when a pull request that includes a change on any file other than README.md
            - README.md
        branches:
                - main     # configure your workflow to only run on pull requests that target specific branch
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo this workflow/job/step is excuted for event type - ${{ github.event_name }}





